"""eddit Account model

Revision ID: 64fa6cc33faa
Revises: d2765bf060d7
Create Date: 2026-06-11 11:39:32.576848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64fa6cc33faa'
down_revision: Union[str, None] = 'd2765bf060d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    # op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    # op.drop_table('auth_user_groups')
    # op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')
    # op.drop_table('django_celery_beat_periodictasks')
    # op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    # op.drop_table('auth_permission')
    # op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    # op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    # op.drop_table('auth_group_permissions')
    # op.drop_table('django_content_type')
    # op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    # op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    # op.drop_table('django_admin_log')
    # op.drop_table('django_migrations')
    # op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    # op.drop_table('auth_group')
    # op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    # op.drop_table('auth_user')
    # op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    # op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    # op.drop_table('auth_user_user_permissions')
    # op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    # op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    # op.drop_table('django_session')
    # op.drop_table('django_celery_beat_intervalschedule')
    # op.drop_table('django_celery_beat_crontabschedule')
    # op.drop_table('django_celery_beat_solarschedule')
    # op.drop_table('django_celery_beat_clockedschedule')
    # op.drop_index('django_celery_beat_periodictask_clocked_id_47a69f82', table_name='django_celery_beat_periodictask')
    # op.drop_index('django_celery_beat_periodictask_crontab_id_d3cba168', table_name='django_celery_beat_periodictask')
    # op.drop_index('django_celery_beat_periodictask_interval_id_a8ca27da', table_name='django_celery_beat_periodictask')
    # op.drop_index('django_celery_beat_periodictask_name_265a36b7_like', table_name='django_celery_beat_periodictask')
    # op.drop_index('django_celery_beat_periodictask_solar_id_a87ce72c', table_name='django_celery_beat_periodictask')
    # op.drop_table('django_celery_beat_periodictask')
    op.add_column('accounts', sa.Column('has_error', sa.Boolean(), server_default='false', nullable=True))
    # op.alter_column('accounts', 'is_active',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.alter_column(
        'accounts',
        'is_active',
        existing_type=sa.String(),
        type_=sa.Boolean(),
        postgresql_using="""
            CASE
                WHEN is_active = 'active' THEN TRUE
                WHEN is_active = 'inactive' THEN FALSE
                ELSE FALSE
            END
        """
    )
    op.drop_column('accounts', 'session')
    op.drop_column('accounts', 'is_parse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_parse', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('session', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('accounts', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('accounts', 'has_error')
    # op.create_table('django_celery_beat_periodictask',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('task', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('args', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('queue', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    # sa.Column('exchange', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    # sa.Column('routing_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    # sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('total_run_count', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('date_changed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('crontab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('interval_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('solar_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('one_off', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('headers', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('clocked_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('expire_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.CheckConstraint('expire_seconds >= 0', name='django_celery_beat_periodictask_expire_seconds_check'),
    # sa.CheckConstraint('priority >= 0', name='django_celery_beat_periodictask_priority_check'),
    # sa.CheckConstraint('total_run_count >= 0', name='django_celery_beat_periodictask_total_run_count_check'),
    # sa.ForeignKeyConstraint(['clocked_id'], ['django_celery_beat_clockedschedule.id'], name='django_celery_beat_p_clocked_id_47a69f82_fk_django_ce', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['crontab_id'], ['django_celery_beat_crontabschedule.id'], name='django_celery_beat_p_crontab_id_d3cba168_fk_django_ce', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['interval_id'], ['django_celery_beat_intervalschedule.id'], name='django_celery_beat_p_interval_id_a8ca27da_fk_django_ce', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['solar_id'], ['django_celery_beat_solarschedule.id'], name='django_celery_beat_p_solar_id_a87ce72c_fk_django_ce', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='django_celery_beat_periodictask_pkey'),
    # sa.UniqueConstraint('name', name='django_celery_beat_periodictask_name_key')
    # )
    # op.create_index('django_celery_beat_periodictask_solar_id_a87ce72c', 'django_celery_beat_periodictask', ['solar_id'], unique=False)
    # op.create_index('django_celery_beat_periodictask_name_265a36b7_like', 'django_celery_beat_periodictask', ['name'], unique=False)
    # op.create_index('django_celery_beat_periodictask_interval_id_a8ca27da', 'django_celery_beat_periodictask', ['interval_id'], unique=False)
    # op.create_index('django_celery_beat_periodictask_crontab_id_d3cba168', 'django_celery_beat_periodictask', ['crontab_id'], unique=False)
    # op.create_index('django_celery_beat_periodictask_clocked_id_47a69f82', 'django_celery_beat_periodictask', ['clocked_id'], unique=False)
    # op.create_table('django_celery_beat_clockedschedule',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('clocked_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_celery_beat_clockedschedule_pkey')
    # )
    # op.create_table('django_celery_beat_solarschedule',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('event', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    # sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    # sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_celery_beat_solarschedule_pkey'),
    # sa.UniqueConstraint('event', 'latitude', 'longitude', name='django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq')
    # )
    # op.create_table('django_celery_beat_crontabschedule',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('minute', sa.VARCHAR(length=240), autoincrement=False, nullable=False),
    # sa.Column('hour', sa.VARCHAR(length=96), autoincrement=False, nullable=False),
    # sa.Column('day_of_week', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    # sa.Column('day_of_month', sa.VARCHAR(length=124), autoincrement=False, nullable=False),
    # sa.Column('month_of_year', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    # sa.Column('timezone', sa.VARCHAR(length=63), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_celery_beat_crontabschedule_pkey')
    # )
    # op.create_table('django_celery_beat_intervalschedule',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('every', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('period', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_celery_beat_intervalschedule_pkey')
    # )
    # op.create_table('django_session',
    # sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    # sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    # )
    # op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    # op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    # op.create_table('auth_user_user_permissions',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    # sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    # )
    # op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    # op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    # op.create_table('auth_user',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    # sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    # sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    # sa.UniqueConstraint('username', name='auth_user_username_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    # op.create_table('auth_group',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    # sa.UniqueConstraint('name', name='auth_group_name_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    # op.create_table('django_migrations',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    # )
    # op.create_table('django_admin_log',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    # sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    # )
    # op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    # op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    # op.create_table('django_content_type',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    # sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('auth_group_permissions',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    # sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    # )
    # op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    # op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    # op.create_table('auth_permission',
    # sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    # sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq')
    # )
    # op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    # op.create_table('django_celery_beat_periodictasks',
    # sa.Column('ident', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('ident', name='django_celery_beat_periodictasks_pkey')
    # )
    # op.create_table('apscheduler_jobs',
    # sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    # sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    # )
    # op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # op.create_table('auth_user_groups',
    # sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    # sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    # sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    # )
    # op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    # op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    # ### end Alembic commands ###
