"""fix: add parse_whole_thread_list filed to Account

Revision ID: af7ae2b683bc
Revises: 7365eaef37d0
Create Date: 2026-08-20 13:28:22.636494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af7ae2b683bc'
down_revision: Union[str, None] = '7365eaef37d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')
    op.add_column('accounts', sa.Column('parse_whole_thread_list', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'parse_whole_thread_list')
    # op.create_table('apscheduler_jobs',
    # sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    # sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    # sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    # )
    # op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
